### ISSUE TITLE
Add class indentation for functions in incomplete code

### ISSUE THREAD

**Issue by blastegit** [DArtagnant/blueJ-code-highlighter#8]
It should be borne in mind that the code sent is not necessarily beautiful java code starting with the declaration of a new class (public class NomdetaClass { ). In the many cases where you only want to display a method, for example, the placement of the method's closing brace is poorly indented

**Comment by DArtagnant** [comment]
Can't reproduce. Do you have screenshots ?

**Comment by DArtagnant** [comment]
In java functions must be in a class. So yes, the class indentation is currently missing for incomplete code.

**Comment by DArtagnant** [comment]
done. please active `functions_always_in_class` and do _not_ mix incomplete code (only functions) with classes because the 'fake' class indentation created for the functions never stops.
